"""base model

Revision ID: 90a22537438b
Revises: 
Create Date: 2023-02-16 15:12:29.657707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90a22537438b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kettle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=124), nullable=True))
        batch_op.add_column(sa.Column('temperature', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kettle', schema=None) as batch_op:
        batch_op.drop_column('temperature')
        batch_op.drop_column('state')

    # ### end Alembic commands ###
