"""deleted boiling_time

Revision ID: f1f255bee0e8
Revises: 90a22537438b
Create Date: 2023-02-17 02:05:35.124330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1f255bee0e8'
down_revision = '90a22537438b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kettle', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=124),
               type_=sa.String(length=60),
               existing_nullable=True)
        batch_op.drop_column('boiling_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kettle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('boiling_time', sa.INTEGER(), nullable=True))
        batch_op.alter_column('state',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=124),
               existing_nullable=True)

    # ### end Alembic commands ###
